### ISSUE TITLE
Going to some websites does not work properly

### ISSUE THREAD

**Issue by pickle69420** [titaniumnetwork-dev/Ultraviolet#63]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior

You should be able to open the website with no errors.

## Current Behavior

It gives me this error:
```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

I'm not sure if it is just my implementation of the proxy.

## Steps to Reproduce

[Personal link to reddit.com](https://picklebox.hop.sh/~uv/hvtrs8%2F-wuw%2Crgdfiv.aoo%2F)

I'm pretty sure Radon Games has this problem too.

1. Go to any proxy site
2. Attempt to go to reddit.com
3. Encounter the error

**Comment by pickle69420** [comment]
It is reachable because websites like google.com are usable.

**Comment by FatGrizzly** [comment]
post ur nginx conf/reverse proxy conf.

**Comment by Limour-dev** [comment]
happening to me too
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/93720049/a1cd30f0-6c05-441c-91e4-1355c2bde9c3)
```bash
mkdir -p ~/app/website && cd ~/app/website && nano Dockerfile && nano docker-compose.yml
git clone --depth=1 https://github.com/holy-unblocker/website-aio.git
sudo docker build -t limour/website .
sudo docker-compose up -d && sudo docker-compose logs
```
```Dockerfile
FROM node:current-alpine3.17
WORKDIR /website-aio
COPY website-aio /website-aio
ENV PORT=8080
RUN npm install
CMD ["npm", "start"]
```
```yml
version: '3.3'
services:
    website:
        container_name: website
        restart: always
        image: limour/website
        ports:
            - '3512:8080'
```

nginx 
```yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/93720049/aca3b6a5-cd79-4a6b-b968-446e9118c72b)
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/93720049/c6d63c9b-8b3d-40a7-9f1f-d278e3485639)
